import $ from "@master/literal";
import Head from "next/head";

export default function Credits() {
  const warriors = [
    { name: "Rodrigo Oler", github: "rodrigooler" },
    { name: "Yan Mendes", github: "kings177" },
    { name: "Vitor Chiarelli", github: "sipher" },
    { name: "Victor Maia", github: "victortaelin" },
    { name: "Leo", github: "derenash" },
    { name: "Kelvin Steiner", github: "steinerkelvin" },
    { name: "Lucas Mello", github: "LucasMauriz" },
    { name: "Rheidner Achiles", github: "racs4" },
    { name: "Marcio Maia", github: "LordEtrius" },
    { name: "Gabriel Sevilha", github: "CorganKnight" },
  ].sort(() => Math.random() - 0.5);

  return (
    <div className="flex flex:col ai:center jc:center h:100vh bg:black gap:20">
      <Head>
        <title>Fibulacci - Kindelia Dapps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Credits</h1>
      <p>Thanks to everyone who helped make this possible!</p>

      <main className="flex w:3/4 flex:wrap @float|3s|ease-in-out">
        {warriors.map((person) => (
          <a
            className={$`
                bg:url('https://github.com/${person.github}.png') 
                h:300 
                w:300
                flex
                flex:wrap
                jc:center
                ai:center
                bg:cover 
                bg:no-repeat 
                opacity:0.3 
                opacity:1:hover 
                cursor:pointer
            `}
            target="_blank"
            href={`https://github.com/${person.github}`}
          >
            <div className="mt:auto flex flex:col jc:center ai:center gap:4 p:10">
              <p className="f:16 text-shadow:1|2|3|black">{person.name}</p>
              <p className="f:10 text-shadow:1|2|3|black">@{person.github}</p>
            </div>
          </a>
        ))}
      </main>
    </div>
  );
}
