import Head from "next/head";
import { useState } from "react";

import { LoadingScreen } from "../components/Screens/LoadingScreen";
import PlayScreen from "../components/Screens/PlayScreen";
import { StartScreen } from "../components/Screens/StartScreen";

export default function Index() {
  const [step, setStep] = useState<0 | 1 | 2>(0);

  return (
    <div>
      <Head>
        <title>Fibulacci - Kindelia Dapps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {
          {
            0: <LoadingScreen setStep={setStep} />,
            1: <StartScreen setStep={setStep} />,
            2: <PlayScreen />,
          }[step]
        }
      </main>
    </div>
  );
}
