import Head from "next/head";
import { Canvas } from "./components/Canvas";
import { useKey } from "react-use";
import { useState } from "react";
import { grass00 } from "./constants";

export default function Home() {
  const [count, set] = useState(0);

  const increment = () => set((count) => ++count);

  useKey("ArrowUp", increment);
  useKey("ArrowRight", increment);
  useKey("ArrowLeft", increment);
  useKey("ArrowDown", increment);

  function draw(context: CanvasRenderingContext2D) {
    let image = new Image();
    
    image.onload = () => { 
      context.drawImage(image, 0, 0)
    }

    image.src = grass00
    image.width = 250
    image.height = 250

    context.fillStyle = 'white';
    context.fillRect(0, 0, 500, 500);
  }

  return (
    <div>
      <Head>
        <title>Fibulacci - Kindelia Dapp's</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Fibulacci</h1>
        <h4>{JSON.stringify({
          count,
        })}</h4>
        <Canvas draw={draw} width={500} height={500} />
      </main>
    </div>
  );
}
