import { Stage } from '@inlet/react-pixi';
import Head from 'next/head';
import { useWindowSize } from 'react-use';

import { Blob } from '../components/Blob';
import { Map } from '../components/Map';
import { Player } from '../components/Player';
import { useKindeliaPostTestMutation } from '../hooks/useKindeliaPostTestMutation';
import { useKindeliaStatsQuery } from '../hooks/useKindeliaStatsQuery';

export default function Home() {
  const window = useWindowSize();

  const stats = useKindeliaStatsQuery();
  const x = useKindeliaPostTestMutation();

  console.log(JSON.stringify(stats));

  return (
    <div>
      <Head>
      <title>Fibulacci - Kindelia Dapps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Stage
          width={window.width}
          height={window.height}
          options={{
            backgroundColor: 0x1099bb,
          }}
        >
          <Map>
            <Player />
            <Blob side="left" x={200} y={400} />
            <Blob side="left" x={250} y={303} />
            <Blob side="right" x={400} y={500} />
          </Map>
        </Stage>
      </main>
    </div>
  );
}
